package models

type ServiceInfo struct {
	IPAddress   string
	Port        string
	ServiceName string
}

type ServicesInfo []ServiceInfo

type Queue struct {
	Name    string `json:"name"`
	Command string `json:"command"`
}

// type QueueList struct {
// 	Queue *[]Queue `json:"queueLsit"`
// }

// Generated by curl-to-Go: https://mholt.github.io/curl-to-go
// curl \
// -X POST \
// -H "Content-Type: application/json" \
// --data '{"operationName":"GetAxieBriefList","query":"query GetAxieBriefList($auctionType: AuctionType, $criteria: AxieSearchCriteria, $from: Int, $sort: SortBy, $size: Int, $owner: String) {\naxies(auctionType: $auctionType, criteria: $criteria, from: $from, sort: $sort, size: $size, owner: $owner) {\n  total\n  results {\n    ...AxieBrief\n    __typename\n  }\n  __typename\n}\n      }\n\n      fragment AxieBrief on Axie {\nid\nname\nstage\nclass\nbreedCount\nimage\ntitle\ngenes\nbattleInfo {\n  banned\n  __typename\n}\nauction {\n  currentPrice\n  currentPriceUSD\n  __typename\n}\nstats {\n  ...AxieStats\n  __typename\n}\nparts {\n  id\n  name\n  class\n  type\n  specialGenes\n  __typename\n}\n__typename\n      }\n    \n      fragment AxieStats on AxieStats {\n       hp\n       speed\n       skill\n       morale\n__typename\n      }","variables":{"auctionType":"Sale","criteria":{"classes":["Plant"],"parts":["mouth-serious","mouth-humorless","horn-little-branch","horn-winter-branch","back-pumpkin","tail-carrot","tail-namek-carrot"],"hp":null,"speed":null,"skill":null,"morale":null,"breedCount":null,"pureness":[5,6],"numMystic":[],"title":null,"region":null,"stages":[3,4]},"from":0,"size":12,"sort":"PriceAsc","owner":null}}' \
// https://axieinfinity.com/graphql-server-v2/graphql

type Payload struct {
	OperationName string    `json:"operationName"`
	Query         string    `json:"query"`
	Variables     Variables `json:"variables"`
}
type Criteria struct {
	Classes    []string      `json:"classes"`
	Parts      []string      `json:"parts"`
	Hp         interface{}   `json:"hp"`
	Speed      interface{}   `json:"speed"`
	Skill      interface{}   `json:"skill"`
	Morale     interface{}   `json:"morale"`
	BreedCount interface{}   `json:"breedCount"`
	Pureness   []int         `json:"pureness"`
	NumMystic  []interface{} `json:"numMystic"`
	Title      interface{}   `json:"title"`
	Region     interface{}   `json:"region"`
	Stages     []int         `json:"stages"`
}
type Variables struct {
	AuctionType string      `json:"auctionType"`
	Criteria    Criteria    `json:"criteria"`
	From        int         `json:"from"`
	Size        int         `json:"size"`
	Sort        string      `json:"sort"`
	Owner       interface{} `json:"owner"`
}
